### PR TITLE
cart_free(): free cart ram/rom

### PR DESCRIPTION
**Pull request by dinkc64**

### CODE REVIEW

**Comment by dinkc64** [comment]
Hi,
The cart_free() change above fixes left-behind chunk(s) of memory after exiting the emulator with snes_free()
snes_setPixelFormat() allows for changing the pixel renderer to RGBX or XRGB; if not called, it defaults to RGBX.

best regards,
- dink

**Comment by dinkc64** [comment]
Now that "the little things" are out of the way, let's do great things! :)

**Comment by angelo-wf** [comment]
Never realised those buffers weren't actually freed on `snes_free`, and being able to set more video output formats can be handy. Thanks for the fixes!

**Comment by dinkc64** [comment]
@angelo-wf thanks! :) You've done such great work on this emu!

best regards,
- dink

**Pull request merged**
